config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  # ログイン関連
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    collection {post :import}
    member do
      # 一ヵ月の勤怠確認申請
      post 'attendance_confirmation/create'
      get 'attendance_confirmation/confirmation'
      patch 'attendance_confirmation/confirmation_update'

      # 勤怠変更申請
      get 'attendances/edit_one_month'
      post 'attendance_change/create'
      get 'attendance_change/change'
      patch 'attendance_change/change_update'
      
      # 勤怠ログ表示
      get 'attendance_change/show'
      
      # 残業申請
      get 'attendance_overtime/new'
      post 'attendance_overtime/create'
      get 'attendance_overtime/overtime'
      patch 'attendance_overtime/overtime_update'
    end
    resources :attendances, only: [:update, :index]
    resources :bases, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  
  validates :affiliation, length: { in: 2..10 }, allow_blank: true
  validates :employee_number, presence: true, length: { is: 4 }, uniqueness: true
  validates :uid, presence: true, length: { is: 4 }, uniqueness: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # トークンをダイジェストに変換する
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ハッシュ化したトークンをDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # remember_digestをnilにする
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # CSVファイルを読み込む、importメソッド。
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = find_by(id: row["id"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
    end
  end

  # # CSVファイルを読み込む、importメソッド。【編集前の保管用】
  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     user = find_by(id: row["id"]) || new
  #     user.attributes = row.to_hash.slice(*updatable_attributes)
  #     user.save
  #   end
  # end

  # importメソッドで更新を許可するカラムを定義
  def self.updatable_attributes
    [
      "name", "email", "affiliation","employee_number","uid",
      "basic_work_time", "designated_work_start_time", "designated_work_end_time",
      "superior", "admin", "password"
    ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]
  before_action :set_one_month, only: :show
  before_action :set_superiors, only: :show
  before_action :logged_in_user, only: [:show, :index, :import, :edit, :update, :destroy]
  before_action :superior_or_correct_user, only: :show
  before_action :admin_user, only: [:index, :edit, :import, :update, :destroy]

  def index
    @users = User.where.not(id: current_user.id).order(id: :asc)
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    
    respond_to do |format|
      format.html
      format.csv do
        send_data render_to_string, filename: "#{@user.name}_#{@first_day.year}年#{@first_day.month}月分.csv", type: :csv
        # send_data render_to_string, filename: "#{@user.name}_#{csv_year}年#{csv_month}月分_#{DateTime.now.strftime("%Y%m%d_%H%M%S")}.csv", type: :csv
      end
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      @users = User.where.not(id: current_user.id).order(id: :asc)
      render :index
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_path
  end
  
  def import
    if params[:file]
      User.import(params[:file])
      flash[:info] = "CSVインポート処理が完了しました。"
      redirect_to users_path
    else
      flash[:danger] = "ファイルを選択してください。"
      redirect_to users_path
    end
    # User.import(params[:file])
    # flash[:info] = "CSVインポート処理が完了しました。"
    # redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(
                                  :name,
                                  :email,
                                  :affiliation,
                                  :employee_number,
                                  :uid,
                                  :basic_work_time,
                                  :designated_work_start_time,
                                  :designated_work_end_time,
                                  :password,
                                  :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報の各時間を指定のフォーマットで返す。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  # params内に[:readonly_flag]が含まれるかどうか確認する
  def hide
    params[:readonly_flag].nil?
  end
  
  # ページ出力前に該当月の「勤怠確認申請」の申請状況を取得する。
  def attendance_confirmation_status_check
    target = AttendanceConfirmation.where(applicant: params[:id], application_month: @first_day).order(created_at: :desc).limit(1)
    if target.empty?
      return "未"
    else
      target.each do |record|
        superior = User.find(record.superior_id)
        return "申請中(#{superior.name})" if record.status == "申請中"
        return "承認済(#{superior.name})" if record.status == "承認"
        return "否認(#{superior.name})" if record.status == "否認"
      end
    end
  end

  # 自身への「勤怠確認申請」の有無、及び未承認・否認件数の確認。
  def notification_confirmation
    unapproved = AttendanceConfirmation.where(superior_id: params[:id], status: "申請中")
    unapproved_comment = "申請中#{unapproved.count}件"
    denial = AttendanceConfirmation.where(superior_id: params[:id], status: "否認")
    denial_comment = "否認#{denial.count}件"
    total_count = unapproved.count + denial.count
    if total_count != 0
      return "#{total_count}件の通知があります。（内訳:#{unapproved_comment}、#{denial_comment}）"
    end
    false
  end
  
  # 自身への「勤怠変更申請」の有無、及び未承認・否認件数の確認。
  def notification_change
    unapproved = AttendanceChange.where(superior_id: params[:id], status: "申請中")
    unapproved_comment = "申請中#{unapproved.count}件"
    denial = AttendanceChange.where(superior_id: params[:id], status: "否認")
    denial_comment = "否認#{denial.count}件"
    total_count = unapproved.count + denial.count
    if total_count != 0
      return "#{total_count}件の通知があります。（内訳:#{unapproved_comment}、#{denial_comment}）"
    end
    false
  end

  # 自身への「残業申請」の有無、及び未承認・否認件数の確認。
  def notification_overtime
    unapproved = AttendanceOvertime.where(superior_id: params[:id], status: "申請中")
    unapproved_comment = "申請中#{unapproved.count}件"
    denial = AttendanceOvertime.where(superior_id: params[:id], status: "否認")
    denial_comment = "否認#{denial.count}件"
    total_count = unapproved.count + denial.count
    if total_count != 0
      return "#{total_count}件の通知があります。（内訳:#{unapproved_comment}、#{denial_comment}）"
    end
    false
  end

  # 承認済みの残業申請がある場合、「業務処理内容」を返す。
  def business_processing_content(day)
    valid_check = AttendanceOvertime.where(
      applicant: day.user_id,
      worked_on: day.worked_on,
      status: "承認"
      ).order(created_at: :desc).limit(1)
    if valid_check.present?
      valid_check.each do |record|
        return "#{record.business_content}"
      end
    end
  end

  # 承認済みの残業申請がある場合、「終了予定時間」の「時」を返す。
  def sheduled_end_at_hour(day)
    valid_check = AttendanceOvertime.where(
      applicant: day.user_id,
      worked_on: day.worked_on,
      status: "承認"
      ).order(created_at: :desc).limit(1)
    if valid_check.present?
      valid_check.each do |record|
        return "#{record.scheduled_end_at.hour}"
      end
    end
  end

  # 承認済みの残業申請がある場合、「終了予定時間」の「分」を返す。
  def sheduled_end_at_min(day)
    valid_check = AttendanceOvertime.where(
      applicant: day.user_id,
      worked_on: day.worked_on,
      status: "承認"
      ).order(created_at: :desc).limit(1)
    if valid_check.present?
      valid_check.each do |record|
        return "#{record.scheduled_end_at.min}"
      end
    end
  end

end

app/views/users/edit.html.erb
<% provide(:title, "基本情報の修正") %>
<h1 class="headline">基本情報の修正</h1>

app/views/users/index.html.erb
<% provide(:title, 'ユーザ一覧') %>
<%= render 'shared/error_messages', object: @user %>

<h1 class="headline">ユーザ一覧</h1>

<div class="row">
  <div class="col-md-3">
    <%= form_tag import_users_path, multipart: true do %>
      <%= file_field_tag :file, class: "file-selection" %>
      <%= submit_tag "CSVをインポート", class: "btn btn-primary btn-block btn-csv-import" %>
    <% end %>
  </div>
</div>

<div calss="row">
  <div class="col-md-10 accordion-index-block">
  <div>Example</div>
    <% @users.each do |user| %>
      <% serial = $alphabet[user.id.to_i - 1] %>
      <%= user.name %>
      <br>
      <a class="delete-button-left"></a>
      <%= 
        link_to "削除", user_path(user), method: :delete, data: { confirm: "「#{user.name}」を削除してよろしいですか？" },
        class: "btn btn-primary btn-user-delete"
      %>
    
      <div class="accordion accordion-block">
        <div class="card">
          <div class="card-header accordion-head--color">
            <button class="btn btn-primary btn-user-edit" type="button"
              data-toggle="collapse" data-target="#card-4<%= serial %>"
              aria-expanded="true" aria-controls="card-4<%= serial %>">
              編集
            </button>
          </div>
          <div id="card-4<%= serial %>" class="collapse"
              aria-labelledby="header-4<%= serial %>" data-parent="#accordion-4">
            <div class="card-body accordion-body">
              <%= form_with(model: user, local: true) do |f| %>
              
                <%= f.label :name, class: "label-user-edit" %>
                <%= f.text_field :name, class: "form-control" %>
              
                <%= f.label :email, class: "label-user-edit" %>
                <%= f.email_field :email, class: "form-control" %>
              
                <%= f.label :affiliation, class: "label-user-edit" %>
                <%= f.text_field :affiliation, class: "form-control" %>
              
                <%= f.label :employee_number, class: "label-user-edit" %>
                <%= f.text_field :employee_number, class: "form-control" %>
              
                <%= f.label :uid, class: "label-user-edit" %>
                <%= f.text_field :uid, class: "form-control" %>
              
                <%= f.label :password, class: "label-user-edit" %>
                <%= f.password_field :password, class: "form-control" %>
              
                <%= f.label :password_confirmation, class: "label-user-edit" %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
              
                <%= f.label :basic_work_time, class: "label-user-edit" %>
                <%= f.time_field :basic_work_time, class: "form-control" %>
              
                <%= f.label :designated_work_start_time, class: "label-user-edit" %>
                <%= f.time_field :designated_work_start_time, class: "form-control" %>
              
                <%= f.label :designated_work_end_time, class: "label-user-edit" %>
                <%= f.time_field :designated_work_end_time, class: "form-control" %>
              
                <%= f.submit "編集する", class: "btn btn-primary btn-block btn-user-update" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<table class="table table-bordered table-condensed table-border-duplication">
  <div class="row">
    <tr>
      <th class="col-md-4 table-head">
        <div>
        <%= link_to "◀", user_path(date: @first_day.prev_month), class: "btn btn-primary" if hide %>
        &nbsp;
        <%= l(@first_day, format: :middle) %>
        &nbsp;
        時間管理表
        &nbsp;
        <%= link_to "▶", user_path(date: @first_day.next_month), class: "btn btn-primary" if hide %>
        </div>
      </th>
      <th class="col-md-2 table-head">
        指定勤務開始時間&emsp;<%= format_basic_info(@user.designated_work_start_time) %>
        <br>
        &nbsp;&nbsp;指定勤務終了時間&emsp;<%= format_basic_info(@user.designated_work_end_time) %>
      </th>
      <th class="col-md-4 table-head"><%= format_basic_info(@user.basic_work_time) %>&emsp;基本時間</th>
      <th class="col-md-2 table-head">初日&emsp;<%= l(@first_day, format: :short_zero) %></th>
    </tr>
  </div>
</table>

<table class="table table-bordered table-condensed center">
  <div class="row">
    <tr>
      <th class="col-md-4 table-head">所属&emsp;<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></th>
      <th class="col-md-2 table-head">氏名&emsp;<%= @user.name %></th>
      <th class="col-md-1 table-head">コード</th>
      <th class="col-md-1 table-head"><%= @user.employee_number %></th>
      <th class="col-md-2 table-head">出勤日数&emsp;<%= @worked_sum %>日</th>
      <th class="col-md-2 table-head">締め&emsp;<%= l(@last_day, format: :short_zero) %></th>
    </tr>
  </div>
</table>

<% if hide %>
  <% if current_user.superior? %>
    <div>
      <% provide(:confirmation, "-confirmation-presence") if notification_confirmation %>
      <%=
        link_to "【所属長承認申請のお知らせ】", attendance_confirmation_confirmation_user_path(@user),
        remote: true, class: "link-notification#{yield(:confirmation)}"
      %>
      <%= notification_confirmation if notification_confirmation %>
      <br>
      <% provide(:change, "-change-presence") if notification_change %>
      <%=
        link_to "【勤怠変更申請のお知らせ】", attendance_change_change_user_path(@user),
        remote: true, class: "link-notification#{yield(:change)}"
      %>
      <%= notification_change if notification_change %>
      <br>
      <% provide(:overtime, "-overtime-presence") if notification_overtime %>
      <%= 
        link_to "【残業申請のお知らせ】", attendance_overtime_overtime_user_path(@user),
        remote:true, class: "link-notification#{yield(:overtime)}"
      %>
      <%= notification_overtime if notification_overtime %>
    </div>
  <% end %>

  <%= 
    link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary"
  %>
  <%= link_to "CSV出力", user_path(format: :csv, date: @first_day), class: "btn btn-primary" %>
  <br>
  <%= link_to "勤怠修正ログ（承認済）", attendance_change_show_user_path(@user, date: @first_day), class: "btn btn-primary btn-attendance-log" %>
  
<% end %>

<table class="table table-bordered table-condensed center table-striped">
  <thead>
    <tr>
      <th rowspan="3" class="table-head">残業申請</th>
      <th rowspan="3" class="table-head">日付</th>
      <th rowspan="3" class="table-head">曜日</th>
      <th colspan="8" class="table-head">【実績】</th>
      <th colspan="5" class="table-head">所定外勤務</th>
    </tr>
    <tr>
      <th colspan="3" class="table-head">出社</th>
      <th colspan="3" class="table-head">退社</th>
      <th rowspan="2" class="table-head">在社時間</th>
      <th rowspan="2" class="table-head">備考</th>
      <th colspan="2" class="table-head">終了予定時間</th>
      <th rowspan="2" class="table-head">時間外時間</th>
      <th rowspan="2" class="table-head">業務処理内容</th>
      <th rowspan="2" class="table-head">指示者確認㊞</th>
    </tr>
    <tr>
      <th class="table-head">時</th>
      <th class="table-head">分</th>
      <th class="table-head"></th>
      <th class="table-head">時</th>
      <th class="table-head">分</th>
      <th class="table-head"></th>
      <th class="table-head">時</th>
      <th class="table-head">分</th>
    </tr>
    <tr>
  </thead>
  <tbody>
    <% @attendances.each do |day| %>
    <tr>
      <td class="table-data">
        <% if hide %>
          <%= link_to "残業申請", attendance_overtime_new_user_path(@user, attendance_id: day), remote: true,
            class: "btn btn-primary" %>
        <% end %>
      </td>
      <td class="table-data"><%= l(day.worked_on, format: :short) %></td>
      <td class='table-data <%= "wday#{day.worked_on.wday}" %>'>
        <%= $days_of_the_week[day.worked_on.wday] %>
      </td>
      <td class="table-data"><%= day.started_at.hour if day.started_at.present? %></td>
      <td class="table-data">
        <%= fifteen_minutes_conversion(day.started_at.min) if day.started_at.present? %>
      </td>
      <td class="table-data">
      <% if hide %>
        <% if btn_text = attendance_state(day) %>
          <%=
            link_to "#{btn_text}", user_attendance_path(@user, day),
            method: :patch, class: "btn btn-primary btn-attendance"
          %>
        <% end %>
      <% end %>
      </td>
      <td class="table-data"><%= day.finished_at.hour if day.finished_at.present? %></td>
      <td class="table-data">
        <%= fifteen_minutes_conversion(day.finished_at.min) if day.finished_at.present? %>
      </td>
      <td></td>
      <td class="table-data">
      <% if day.started_at.present? && day.finished_at.present? %>
        <%= str_times = working_times(day.started_at, day.finished_at, day.next_day_flag) %>
        <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
      <% end %>
      </td>
      <td class="table-data"><%= approved_remarks(day) %></td>
      <td class="table-data"><%= sheduled_end_at_hour(day) %></td>
      <td class="table-data"><%= sheduled_end_at_min(day) %></td>
      <td class="table-data">
        <% if day.started_at.present? && day.finished_at.present? %>
          <% over_time = working_times_over(day.started_at, day.finished_at, day.next_day_flag) %>
          <%= over_time if over_time.to_i >= 0.01 %>
        <% end %>
      </td>
      <td class="table-data"><%= business_processing_content(day) %></td>
      <td class="table-data">
        <% first_line = overtime_status_display(day) %>
        <% second_line = change_status_display(day) %>
        <% if first_line && second_line %>
          <%= first_line %><br><%= second_line %>
        <% else %>
          <%= first_line %><%= second_line %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
  
  <tfoot class="table-foot">
    <td colspan="1"></td>
    <td colspan="2"></td>
    <td colspan="6"></td>
    <td class="table-data"><%= format("%.2f", @total_working_times.to_f) %></td>
    <td colspan="5"></td>
    <td colspan="1">
      <div>
      所属長承認&emsp;<%= attendance_confirmation_status_check %>
      <% if hide %>
        <%= form_with(model: @user, url: attendance_confirmation_create_user_path, local: true, method: :post) do |f| %>
          <%= f.hidden_field(:applicant, value: @user.id) %>
          <%= f.hidden_field(:application_month, value: @first_day) %>
          <%= f.collection_select(:superior_id, @superiors, :id, :name, {:include_blank => true}, class: "select-attendance-confirmation") %>
          <%= f.hidden_field(:status, value: "申請中") %>
          <%= f.submit "申請", class: "btn-attendance-confirmation btn btn-primary btn-lg" %>
        <% end %>
      <% end %>
      </div>
    </td>
  </tfoot>
</table>

<!--モーダルウインドウ表示-->
<div id="confirmation" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="change" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>