config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  # ログイン関連
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    collection {post :import}
    member do
      # 一ヵ月の勤怠確認申請
      post 'attendance_confirmation/create'
      get 'attendance_confirmation/confirmation'
      patch 'attendance_confirmation/confirmation_update'

      # 勤怠変更申請
      get 'attendances/edit_one_month'
      post 'attendance_change/create'
      get 'attendance_change/change'
      patch 'attendance_change/change_update'
      
      # 勤怠ログ表示
      get 'attendance_change/show'
      
      # 残業申請
      get 'attendance_overtime/new'
      post 'attendance_overtime/create'
      get 'attendance_overtime/overtime'
      patch 'attendance_overtime/overtime_update'
    end
    resources :attendances, only: [:update, :index]
    resources :bases, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  # 出勤時間が存在しない場合に、退勤時間を無効にする
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  # 出勤・退勤時間がどちらも存在する時、出勤時間より早い退勤時間を無効にする
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: :edit_one_month
  before_action :set_one_month, only: :edit_one_month
  before_action :set_superiors, only: :edit_one_month
  before_action :logged_in_user, only: [:update, :edit_one_month, :index]
  before_action :correct_user, only: [:update, :edit_one_month]
  before_action :admin_user, only: :index
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def index
    jobs = Attendance.where(worked_on: Date.current, finished_at: nil)
    jobs = jobs.where.not(started_at: nil)
    @jobs_array = []
    jobs.each do |job|
      @jobs_array.push(User.find(job.user_id))
    end
  end

  def edit_one_month
  end

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper

  # 出社・退社ボタンの表示/非表示の判定材料を返す。
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  # 在社時間を計算して返す。15分単位ver
  def working_times(start, finish, next_day_flag)
    start_time = start.hour * 60 + fifteen_minutes_conversion(start.min)
    if next_day_flag
      finish_time = (finish.hour + 24) * 60 + fifteen_minutes_conversion(finish.min)
    else
      finish_time = finish.hour * 60 + fifteen_minutes_conversion(finish.min)
    end
    format("%.2f", (finish_time - start_time) / 60.0)
  end

  # 時間外時間を計算して返す。15分単位ver
  def working_times_over(start, finish, next_day_flag)
    start_time = start.hour * 60 + fifteen_minutes_conversion(start.min)
    if next_day_flag
      finish_time = (finish.hour + 24) * 60 + fifteen_minutes_conversion(finish.min)
    else
      finish_time = finish.hour * 60 + fifteen_minutes_conversion(finish.min)
    end
    format("%.2f", ((finish_time - start_time) / 60.0) - 9)
  end

  # 勤怠表示画面の時刻表示（分）を15分単位にする。
  def fifteen_minutes_conversion(time)
    if time <= 14
      0
    elsif time <= 29
      15
    elsif time <= 44
      30
    else
      45
    end
  end
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<%= 
  form_with(model: @attendances, url: attendance_change_create_user_path(date: @first_day),
  local: true) do |f|
%>
  <table class="table table-bordered table-condensed center table-striped">
    <thead>
      <div class="row">
        <tr>
          <th class="col-md-1 table-head">日付</th>
          <th class="col-md-1 table-head">曜日</th>
          <th class="col-md-2 table-head">出社</th>
          <th class="col-md-2 table-head">退社</th>
          <th class="col-md-1 table-head">翌日</th>
          <th class="col-md-1 table-head">在社時間</th>
          <th class="col-md-2 table-head">備考</th>
          <th class="col-md-1 table-head">指示者確認㊞</th>
        </tr>
      </div>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendance_change[]", day do |attendance| %>
          <tr>
            <%= attendance.hidden_field(:applicant, value: @user.id) %>
            <td class="table-data"><%= l(day.worked_on, format: :short) %></td>
              <%= attendance.hidden_field(:worked_on) %>
            <td class='table-data <%= "wday#{day.worked_on.wday}" %>'>
              <%= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <% if day.worked_on > Date.current %>
              <td class="table-data">
                <%= attendance.time_select :started_at, include_blank: true, disabled: true, class: "form-control" %>
              </td>
              <td class="table-data">
                <%= attendance.time_select :finished_at, include_blank: true, disabled: true, class: "form-control" %>
              </td>
            <% else %>
              <td class="table-data"><%= attendance.time_select :started_at, include_blank: true, class: "form-control" %></td>
              <td class="table-data"><%= attendance.time_select :finished_at, include_blank: true, class: "form-control" %></td>
            <% end %>
            <td class="table-data"><%= attendance.check_box :next_day_flag %></td>
            <td class="table-data">
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at, day.next_day_flag) %>
              <% end %>
            </td>
            <td class="table-data"><%= attendance.text_field :note, class: "form-control" %></td>
            <%= attendance.hidden_field(:status, value: "申請中") %>
            <td class="table-data"><%= attendance.collection_select(:superior_id, @superiors, :id, :name, {:include_blank => true}, class: "select-attendance-confirmation") %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <div class="center btn-change-application">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-primary btn-lg" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/attendances/index.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1 class="headline">出勤中社員一覧</h1>

<div class="row">
  <table class="table table-bordered table-condensed center">
    <thead>
      <tr>
        <th class="col-md-6 table-head">社員番号</th>
        <th class="col-md-6 table-head">名前</th>
      </tr>
    </thead>
    
    <tbody>
      <% @jobs_array.each do |job| %>
        <tr>
          <td><%= job.employee_number %></td>
          <td><%= job.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>