config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  # ログイン関連
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    collection {post :import}
    member do
      # 一ヵ月の勤怠確認申請
      post 'attendance_confirmation/create'
      get 'attendance_confirmation/confirmation'
      patch 'attendance_confirmation/confirmation_update'

      # 勤怠変更申請
      get 'attendances/edit_one_month'
      post 'attendance_change/create'
      get 'attendance_change/change'
      patch 'attendance_change/change_update'
      
      # 勤怠ログ表示
      get 'attendance_change/show'
      
      # 残業申請
      get 'attendance_overtime/new'
      post 'attendance_overtime/create'
      get 'attendance_overtime/overtime'
      patch 'attendance_overtime/overtime_update'
    end
    resources :attendances, only: [:update, :index]
    resources :bases, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <% if logged_in? %>
        <% unless current_user.admin? %>
          <% provide(:logo, user_path(current_user)) %>
        <% else %>
          <% provide(:logo, users_path) %>
        <% end %>
      <% else %>
        <% provide(:logo, login_path) %>
      <% end %>
      <%= link_to "勤怠システム", yield(:logo), class: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? && current_user.admin? %>
            <li><%= link_to "トップへ", users_path %></li>
          <% elsif logged_in? && !current_user.admin? %>
            <li><%= link_to "トップへ", user_path(current_user) %></li>
          <% else %>
            <li><%= link_to "トップへ", root_path %></li>
          <% end %>
          
          <% unless logged_in? %>
            <li><%= link_to "ログイン", login_path %></li>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", user_attendances_path(current_user) %></li>
            <li><%= link_to "拠点情報の修正", user_bases_path(current_user) %></li>
            <li><%= link_to "基本情報の修正", edit_user_path(current_user) %></li>
          <% end %>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                アカウント <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="body-common">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>